Numpy is one of the most important library in python. It is basically used for creating multidimension arrays and has lot of inbuild functions which helps to perform different array operations. One can also do scientific operations by using scipy.

an Array is a data structure that stores values of same data type. The difference b/w array and list is, in List one can
store different types of data types whereas in array only same data type values can be stored.

In [1]:
import numpy as np
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [5]:
array.shape

(5,)

In [3]:
type(array)

numpy.ndarray

In [4]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,0]
lst3 = [9,8,7,4,5]
array1 = np.array([lst1,lst2,lst3])
array1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [9, 8, 7, 4, 5]])

In [5]:
array1.shape

(3, 5)

In [7]:
array1.reshape(5,3)   # you can reshape. 3x5  the total count of elements must be same

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 9, 8],
       [7, 4, 5]])

# indexing   # to retrieve the data inside

In [8]:
array

array([1, 2, 3, 4, 5])

In [9]:
array[2]

3

In [11]:
array1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [9, 8, 7, 4, 5]])

In [18]:
array1[1:,:2]

array([[6, 7],
       [9, 8]])

In [19]:
array1[:2,2:4]

array([[3, 4],
       [8, 9]])

In [20]:
array1[1,1:4]

array([7, 8, 9])

arange()   it creates one dimension array and starts from 0

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.arange(10, step = 2)   # steps is the interval
arr

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(1,10,20)   # how many points you want between the start value and end value. equal difference 

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[3:]=20  # 3rd element onwards displaying 20 for the rest of the fields in the array.
arr

array([ 0,  1,  2, 20, 20, 20, 20, 20, 20, 20])

In [31]:
arr1 = arr
arr1[3:] = 50
arr1

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [35]:
np.linspace(2,20,35 , retstep = True)  #  retstep : it returns the stepsize that has been taken

(array([ 2.        ,  2.52941176,  3.05882353,  3.58823529,  4.11764706,
         4.64705882,  5.17647059,  5.70588235,  6.23529412,  6.76470588,
         7.29411765,  7.82352941,  8.35294118,  8.88235294,  9.41176471,
         9.94117647, 10.47058824, 11.        , 11.52941176, 12.05882353,
        12.58823529, 13.11764706, 13.64705882, 14.17647059, 14.70588235,
        15.23529412, 15.76470588, 16.29411765, 16.82352941, 17.35294118,
        17.88235294, 18.41176471, 18.94117647, 19.47058824, 20.        ]),
 0.5294117647058824)

In [33]:
arr    # since array is a reference type and sharing the same memory space , the arr1 value referenced to arr also. 
        # to overcome this we use copy() function

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [34]:
arr2=arr.copy()

In [35]:
arr2[3:] = 60
arr2

array([ 0,  1,  2, 60, 60, 60, 60, 60, 60, 60])

In [36]:
arr   # since copy function used in arr2, the value is not passed to arr

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [41]:
# Conditions that can be used in exploratory data analysis
v=2
arr<2




array([ True,  True, False, False, False, False, False, False, False,
       False])

In [42]:
arr*2  # all types of operations can be done

array([  0,   2,   4, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr<20

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [27]:
arr[arr<20]  # all values which are less than 50 and the values are diplayed when retrieving

array([0, 1, 2])

In [30]:
np.mat('1 2; 3 4')  # creating matrix through numpy

matrix([[1, 2],
        [3, 4]])

In [ ]:
np.mat(np.array([[1, 2],[4,7]]))  creating matrix using np.array function

In [39]:
a= np.random.randint(10,50,(4,4))
a

array([[29, 38, 48, 30],
       [47, 41, 46, 29],
       [20, 33, 34, 19],
       [37, 14, 20, 18]])

In [4]:
np.random.random_sample((2,5))

array([[0.67061067, 0.56739283, 0.10922823, 0.40308647, 0.92881646],
       [0.01473521, 0.44507632, 0.19898752, 0.34510234, 0.0420016 ]])